---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

# 1
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - include_tasks: configuration_tasks.yml

# 2
- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - include_tasks: haproxy.yml

# 3
- name: deploy tomcat
  hosts: apps
  gather_facts: true
  become: true

  tasks:
  - include_tasks: tomcat.yml  
    # ansible_hostname: {{ ansible_hostname }}

# 4
- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - include_tasks: postgres.yml
    tags:
    - db
    
  handlers:
  - name: initialize postgres
    command: "postgresql-setup initdb"
  - name: check postgres config
    command: "chkconfig postgresql on"
  - name: start postgres
    service:
      name: postgresql.service
      state: started